app_spamrecognizer/urls.py
from django.conf.urls import url
from .views import index, main

urlpatterns = [
    # index
    url(r'^$', index, name='index'),
    url(r'^main/$', main, name='main')
]

spamRecognizer/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import app_spamrecognizer.urls as app_spamrecognizer
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^spam/', include(app_spamrecognizer,namespace='spam')),
    url(r'^$', RedirectView.as_view(url = "/spam/", permanent = "true"), name = 'index'),
]

app_spamrecognizer/models.py
from django.db import models

# Create your models here.

app_spamrecognizer/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
import pandas as pd
import string
import json
import random

# Method awal untuk merender halaman html
def index(request):
	temp = getTest()
	response = {'hasil': temp}
	html = 'app_spamrecognizer/spamrecognizer.html'
	return render(request, html, response)

# Method untuk mengolah input yang diberikan untuk menghasilkan output spam atau not spam dari text yang diberikan
@csrf_exempt
def main(request):
	if request.method == 'POST':
		string = request.POST['paramm']
		senArr = string.lower().split(" ")
		dictio = getDict()
		dictTrain, dictTest, labelTrain, labelTest = testing(dictio)
		arrTemp = start(senArr,dictTrain,labelTrain)
		temp = abs(arrTemp[0] - arrTemp[1]) < 0.0001 
		if (arrTemp[0] > arrTemp[1]):   
			res = {"hasil":"Text tersebut adalah spam"}
			return JsonResponse(res)
		else:
			res = {"hasil":"Text tersebut bukan spam"}
			return JsonResponse(res)

# Method untuk melakukan testing pada agent yang dibuat (mencari akurasi)
def getTest():
	dictio = getDict()
	dictTrain, dictTest, labelTrain, labelTest = testing(dictio)
	akurasi,true_positive, true_negative, false_positive, false_negative = getAccuracy(dictTrain,labelTrain,dictTest,labelTest)
	res = str(akurasi)+"%"
	return res

def start(senArr,dictTrain,labelTrain):
	probArr = InitProb(labelTrain) # Return array of probability spam and not spam
	dictWordSpam = {}
	dictWordNotSpam = {}
	dictTotal = {}
	# Loop untuk mengiterasi inputan per kata untuk dibuang tanda bacanya lalu dicari kemunculan kata tersebutdi dataset
	# baik kata tersebut spam atau not spam juga akan dihitung kemunculannya, lalu gabungan dari kemunculan kata di bagian spam dan not spam
	# akan digabungkan di dictionary bernama dictTotal, dengan key = kata dan value adalah total kemunculan kata tersebut (di spam dan not spam)
	for iter1 in senArr: 
		iter1 = iter1.strip(string.punctuation)
		counterSpam = 0
		counterNotSpam = 0
		for iter2 in dictTrain:
			if (iter1 in iter2.lower()):
				if(dictTrain[iter2] == 0 or dictTrain[iter2] == 2):
					counterNotSpam+=1
				elif(dictTrain[iter2] == 1):
					counterSpam+=1
			dictWordSpam[iter1] = counterSpam
			dictWordNotSpam[iter1] = counterNotSpam
			dictTotal[iter1] = counterSpam+counterNotSpam

	# Memanggil method hitunganProb untuk melakukan penghitungan tahap akhir yang akan mencari nilai probabilitas yang sebenarnya (untuk
	# menghindari adanya nilai 0 pada kemunculan kata dari input)
	arrHasil = hitunganProb(dictWordSpam, dictWordNotSpam, dictTotal, probArr)
	hasilSpam = arrHasil[0]*probArr[1]
	hasilNotSpam = arrHasil[1]*probArr[3]
	return [hasilSpam, hasilNotSpam]

# Method untuk membaca dataSet dari file .csv menjadi dictionary dengan key = pesan, dan valuenya = label
def getDict():
	# Untuk baca dataset tabelnya
	readData = pd.read_csv('app_spamrecognizer/dataSet.csv')
	dictio = {}
	teksSMS = readData['Teks']
	listLabel = readData['label']
	for i in range(0, len(listLabel)):  # Membaca teks SMS dan labelnya yang akan diinput ke dictionary
		dictio[teksSMS[i]] = listLabel[i]
	return dictio

def testing(dictio): #generate data dan label train beserta data dan label test sebanyak 100 data
	dictTrain = {}
	dictTest = {}
	labelTrain = []
	labelTest = []
	allKey = list(dictio.keys())
	cnt = 1
	for i in allKey:
		if(cnt <= 100):
			dictTest[i] = dictio[i]
			labelTest.append(dictio[i])
		else:
			dictTrain[i] = dictio[i]
			labelTrain.append(dictio[i])
		cnt+=1
	return [dictTrain,dictTest,labelTrain,labelTest]

# Method untuk mengkalkulasi nilai probabilitas tahap akhir per kata sesuai dengan rumus probabilitas yang diberikan
def hitunganProb(dictWordSpam, dictWordNotSpam, dictTotal, probArr):
	hasilAllWordSpam = 1
	hasilAllwordNotSpam = 1
	arrHasil = list(dictTotal.values())
	konstanta = 1
	peluangBantuan = 0.5
	i = 0
	j = 0
	for iter1 in dictWordSpam:
		tempNilai = (dictWordSpam[iter1]/(probArr[0]+probArr[2]))
		temp = tempNilai/probArr[1]
		res = (konstanta*peluangBantuan + arrHasil[i]*temp)/(konstanta+arrHasil[i])
		hasilAllWordSpam = hasilAllWordSpam*res
		i = i+1
	for iter2 in dictWordNotSpam:
		tempNilai = (dictWordNotSpam[iter2]/(probArr[0]+probArr[2]))
		temp = tempNilai/probArr[3]
		res = (konstanta*peluangBantuan + arrHasil[j]*temp)/(konstanta+arrHasil[j])
		hasilAllwordNotSpam = hasilAllwordNotSpam*res
		j = j+1
	return [hasilAllWordSpam, hasilAllwordNotSpam]

def getAccuracy(dictTrain,labelTrain,dictTest,labelTest): #mendapatkan akurasi dari data test
	true_positive = 0
	false_positive = 0
	true_negative = 0
	false_negative = 0

	listStatus = translateLabelToStatus(labelTest)
	hasilTest = []
	for i in dictTest.keys():
		messageTest = i
		arrTemp = start(messageTest.split(" "),dictTrain,labelTrain)

		if (arrTemp[0] > arrTemp[1]):
			hasilTest.append("s")# Kondisi untuk mengecek nilai dari perbandingan nilai probabilitas spam dan not spam
		else:
			hasilTest.append("ns")

	# Mengiterasi array berupa kumpulan label untuk mencari nilai True Positive, False Positive, True Negative, dan False Negative
	length = len(listStatus)
	for i in range(length):
		if(hasilTest[i] == "s" and listStatus[i] == hasilTest[i]):
			true_positive += 1
		elif(hasilTest[i] == "ns" and listStatus[i] == hasilTest[i]):
			true_negative += 1
		elif(hasilTest[i] == "s" and listStatus[i] != hasilTest[i]):
			false_positive += 1
		else:
			false_negative += 1

	return [((true_positive+true_negative)/length)*100,true_positive,true_negative,false_positive,false_negative]

# Method untuk mentranslate nilai dari label yang diberikan dari 0, 1, 2 menjadi s (untuk 1) dan ns (untuk 0 dan 2)
def translateLabelToStatus(label): #translate dari label yg tadinya 0,1,2 jadi "s" dan "ns"
	listStatus = []
	for i in label:
		if(i == 0 or i == 2):
			listStatus.append("ns")
		else:
			listStatus.append("s")
	return listStatus

def InitProb(listLabel):    # Method untuk mengkalkulasi nilai spam dan not spam dari dataSet yang ada (didapatkan dari nilai label)
							 # untuk label 1 = spam, dan 0 serta 2 merupakan not spam
	hasilSpam = 0
	hasilBknSpam = 0
	for i in listLabel:
		if i == 2 or i == 0:
			hasilBknSpam+=1
		elif i == 1:
			hasilSpam+=1
	temp1 = hasilSpam
	temp2 = hasilBknSpam
	hasilSpam = hasilSpam/len(listLabel)
	hasilBknSpam = hasilBknSpam/len(listLabel)
	return [temp1, hasilSpam, temp2, hasilBknSpam]

app_spamrecognizer/templates/app_spamrecognizer/layout/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="Spam Recognizer AI">
    <meta name="author" content="Intelligent Group">
    <!-- bootstrap css -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">    
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
	<script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <title> 
        {% block title %} Spam Recognizer AI4ID oleh Intelligent Group{% endblock %}
    </title>
</head>
<body background="https://images.pexels.com/photos/160107/pexels-photo-160107.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940">
    <content>
        {% block content %}
                <!-- content goes here -->
        {% endblock %}
    </content>
   <!-- Jquery n Bootstrap Script -->
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
   <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   {% block javascript %}
   {% endblock %}
</body>
<footer class="section footer-classic context-dark bg-image" style="background: #2d3246;margin-top:50px;">
        <div class="container">
          <div class="row row-30">
            <div class="col-md-4 col-xl-5">
              <div class="pr-xl-4"><a class="brand"><img class="brand-logo-light" src="images/agency/logo-inverse-140x37.png" alt="" width="140" height="37" srcset="images/agency/logo-retina-inverse-280x74.png 2x"></a>
                <p>Kami adalah ketiga orang anak bangsa yang mengembangkan aplikasi spam recognizer, yang diharapkan mampu untuk
				membantu Masyarakat Indonesia dalam mengenali pesan yang merupakan spam dan yang bukan spam.</p>
                <!-- Rights-->
                <p class="rights"><span>© Hak Cipta Intelligent Group </span><span class="copyright-year">2018 AI4ID</span><span>. </span></p>
              </div>
            </div>
            <div class="col-md-4">
              <h5>Kontak</h5>
              <dl class="contact-list">
                <dt>Alamat:</dt>
                <dd>Fakultas Ilmu Komputer, Universitas Indonesia, Jawa Barat.</dd>
              </dl>
              <dl class="contact-list">
                <dt>Email:</dt>
                <dd>IGAI4ID@gmail.com</dd>
              </dl>
              <dl class="contact-list">
                <dt>Nomor Telepon:</dt>
                <dd>082123232645 <span>atau</span> 02154637863
                </dd>
              </dl>
            </div>
            <div class="col-md-4 col-xl-3" style="margin-top:10px">
			<dl class="contact-list">
				<dt>Nama Anggota (Kontributor):</dt>
			</dl>
              <ul class="nav-list">
                <li>Aditya Yudha Pratama - 1606917683</li>
                <li>Alif Ahsanil Satria - 1606882540</li>
                <li>Winston Chandra - 1606831294</li>
              </ul>
            </div>
          </div>
        </div>
      </footer>
</footer>
<style>
.context-dark, .bg-gray-dark, .bg-primary {
    color: rgba(255, 255, 255, 0.8);
}

.footer-classic a, .footer-classic a:focus, .footer-classic a:active {
    color: #ffffff;
}
.nav-list li {
    padding-top: 5px;
    padding-bottom: 5px;
}

.nav-list li a:hover:before {
    margin-left: 0;
    opacity: 1;
    visibility: visible;
}

ul, ol {
    list-style: none;
    padding: 0;
    margin: 0;
}

.social-inner {
    display: flex;
    flex-direction: column;
    align-items: center;
    width: 100%;
    padding: 23px;
    font: 900 13px/1 "Lato", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
    text-transform: uppercase;
    color: rgba(255, 255, 255, 0.5);
}
.social-container .col {
    border: 1px solid rgba(255, 255, 255, 0.1);
}
.nav-list li a:before {
    content: "\f14f";
    font: 400 21px/1 "Material Design Icons";
    color: #4d6de6;
    display: inline-block;
    vertical-align: baseline;
    margin-left: -28px;
    margin-right: 7px;
    opacity: 0;
    visibility: hidden;
    transition: .22s ease;
}
</style>
</html>

app_spamrecognizer/templates/app_spamrecognizer/partials/footer.html
<p style = "text-align: center; color:red;">&copy; Intelligent Group</p>

app_spamrecognizer/templates/app_spamrecognizer/spamrecognizer.html
{% extends "app_spamrecognizer/layout/base.html" %}
{% block content %}
<h1 style="text-align:center;color: #ffec8b;font-family:Verdana">
Selamat datang di Spam Recognizer AI</h1>
<h3 style = "text-align: center; color:#ffec8b;font-style:Verdana">Dengan Akurasi sebesar {{ hasil }}</h3>
<br>
<div>
<textarea id="temp" style="resize:none;width:500px;height:500px;font-size:18px;
	margin-left:100px;" placeholder = "Mohon masukkan inputan di dalam kotak ini..."></textarea>
<input id = "but" type="submit" class="btn btn-success" value="Proses" 
	style="margin-left:30px;margin-top:-950px">
</input>
<textarea placeholder = "Ini adalah kotak output dari olahan pesan yang diberikan..." id = "res" 
style="resize:none;width:500px;height:70px;margin-left:30px;font-size:18px;margin-bottom:430px;" readonly>
</textarea>
</div>
<style>
.loader {
  border: 16px solid #f3f3f3;
  border-radius: 50%;
  border-top: 16px solid #3498db;
  width: 120px;
  height: 120px;
  -webkit-animation: spin 2s linear infinite; /* Safari */
  animation: spin 2s linear infinite;
}

/* Safari */
@-webkit-keyframes spin {
  0% { -webkit-transform: rotate(0deg); }
  100% { -webkit-transform: rotate(360deg); }
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
</style>
{% endblock %}
{% block javascript %}
<script>
	var func = function(param){
		console.log(param);
		$.ajax({
			method: "POST",
			url: '{% url "spam:main" %}',
			data: { paramm:param },
			dataType: 'json',
			success : function(response) {
				console.log(response);
				if ($('#res').val() != '') {
					$('#res').val('');
					$('#res').val(response.hasil);
				}
				else {
					$('#res').val(response.hasil);
				}
			},
			error : function(error) {
				console.log(error);
				alert("Mohon dicoba lagi");
			}
		})
	};
	$("#but").button().click(function (event) {
		$('#res').val('Mohon tunggu....');
		var value = $("#temp").val();
		func(value);
		event.preventDefault();
	});
</script>
{% endblock %}